# Generated by Django 3.2.8 on 2021-10-22 18:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('doctorPortal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorsModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('specialize', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('mobile', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PateintFeestatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PateintModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=150)),
                ('symptoms', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=20)),
                ('feeStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorPortal.pateintfeestatus')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('time', models.DateField(default=django.utils.timezone.now)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorPortal.doctorsmodel')),
                ('pateint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorPortal.pateintmodel')),
            ],
        ),
    ]
