# Generated by Django 3.0.14 on 2021-10-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorPortal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorsmodel',
            name='salary',
            field=models.IntegerField( verbose_name='salary of Doctor'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
